G1int/Glint_BE

glint/build.gradle

fix: #4 : rds 연동 개발

---

glint/build.gradle
glint/src/main/java/com/swyp/glint/system/aop/LoggingAspect.java
glint/src/main/java/com/swyp/glint/system/aop/PointCuts.java
glint/src/main/java/com/swyp/glint/system/config/LogTraceConfig.java
glint/src/main/java/com/swyp/glint/system/util/logtrace/LogTrace.java
glint/src/main/java/com/swyp/glint/system/util/logtrace/ThreadLocalLogTrace.java
glint/src/main/java/com/swyp/glint/system/util/logtrace/TraceId.java
glint/src/main/java/com/swyp/glint/system/util/logtrace/TraceStatus.java
glint/src/main/resources/application.yaml

feat: #14 : 로깅 개발

---

glint/build.gradle
glint/src/main/java/com/swyp/glint/auth/application/UserPrincipalDetails.java
glint/src/main/java/com/swyp/glint/auth/application/UserPrincipalDetailsService.java
glint/src/main/java/com/swyp/glint/auth/filter/JwtLoginFilter.java
glint/src/main/java/com/swyp/glint/common/authority/AuthorityHelper.java
glint/src/main/java/com/swyp/glint/common/baseentity/BaseTimeEntity.java
glint/src/main/java/com/swyp/glint/common/cache/RemoteCache.java
glint/src/main/java/com/swyp/glint/common/util/CookieUtil.java
glint/src/main/java/com/swyp/glint/common/util/RedisUtil.java
glint/src/main/java/com/swyp/glint/system/config/CorsConfig.java
glint/src/main/java/com/swyp/glint/system/config/RedisConfig.java
glint/src/main/java/com/swyp/glint/system/config/SecurityConfig.java
glint/src/main/java/com/swyp/glint/user/domain/InformationKeyword.java
glint/src/main/java/com/swyp/glint/user/domain/UserDetail.java
glint/src/main/java/com/swyp/glint/user/domain/UserProfile.java
glint/src/main/resources/application.yaml

❗️ 이슈 번호
close #19
📝 작업 내용
- 레디스 캐시 세팅
- 쿠키 유팅 개발
- accessToken, refreshToken 개발
🙇🏻‍♂️ 참고사항!
💡 참고 자료

Feat #19 토큰인증,인가

---

glint/src/main/java/com/swyp/glint/auth/api/AuthController.java
glint/src/main/java/com/swyp/glint/user/application/dto/UserDTO.java
glint/src/main/java/com/swyp/glint/user/application/dto/UserLoginResponse.java
glint/src/main/java/com/swyp/glint/user/application/dto/UserRequest.java
glint/src/main/java/com/swyp/glint/user/application/dto/UserResponse.java
glint/src/main/java/com/swyp/glint/user/domain/User.java
glint/src/main/java/com/swyp/glint/user/domain/UserDetail.java
glint/src/main/java/com/swyp/glint/user/domain/UserProfile.java
glint/src/main/resources/application.yaml

❗️ 이슈 번호
close #29
📝 작업 내용
- 유저 response 수정
- 카카오 로그인 client-id 수정

fix: #29 : 유저 response 수정

---

glint/src/main/java/com/swyp/glint/GlintApplication.java
glint/src/main/java/com/swyp/glint/auth/api/AuthController.java
glint/src/main/java/com/swyp/glint/user/application/dto/UserDTO.java
glint/src/main/java/com/swyp/glint/user/application/dto/UserLoginResponse.java
glint/src/main/java/com/swyp/glint/user/application/dto/UserRequest.java
glint/src/main/java/com/swyp/glint/user/application/dto/UserResponse.java
glint/src/main/java/com/swyp/glint/user/domain/User.java
glint/src/main/java/com/swyp/glint/user/domain/UserDetail.java
glint/src/main/java/com/swyp/glint/user/domain/UserProfile.java
glint/src/main/resources/application.yaml

release merge 

---

glint/build.gradle
glint/src/main/java/com/swyp/glint/common/exception/FileNotFoundException.java
glint/src/main/java/com/swyp/glint/image/api/ImageController.java
glint/src/main/java/com/swyp/glint/image/application/AmazonFileUploadService.java
glint/src/main/java/com/swyp/glint/image/application/FileUploadService.java
glint/src/main/java/com/swyp/glint/image/application/ImageService.java
glint/src/main/java/com/swyp/glint/image/application/dto/ImageResponse.java
glint/src/main/java/com/swyp/glint/image/domain/ProfileImageFile.java
glint/src/main/java/com/swyp/glint/system/config/S3Config.java
glint/src/main/resources/application.yaml

❗️ 이슈 번호
close #34
📝 작업 내용
- 유저 프로필 이미지 업로드 api
- 인증 자료 이미지 업로드 api

fix: #34 : 이미지 업로드

---

glint/src/main/java/com/swyp/glint/auth/filter/JwtLoginFilter.java
glint/src/main/java/com/swyp/glint/chatting/config/WebSocketConfig.java
glint/src/main/java/com/swyp/glint/system/config/CorsConfig.java
glint/src/main/java/com/swyp/glint/system/config/SecurityConfig.java
glint/src/main/java/com/swyp/glint/system/config/WebMvcConfig.java
glint/src/main/java/com/swyp/glint/user/application/UserDetailService.java
glint/src/main/java/com/swyp/glint/user/domain/UserDetail.java

❗️ 이슈 번호
close #56 
📝 작업 내용
- 임시 userDetail이 중복으로 들어가는 현상 수정

Fix #56 유저 아이디 중복검사

---

glint/src/main/java/com/swyp/glint/keyword/api/DrinkingController.java
glint/src/main/java/com/swyp/glint/keyword/api/LocationController.java
glint/src/main/java/com/swyp/glint/keyword/api/ReligionController.java
glint/src/main/java/com/swyp/glint/keyword/api/SmokingController.java
glint/src/main/java/com/swyp/glint/keyword/api/UniversityController.java
glint/src/main/java/com/swyp/glint/keyword/api/WorkController.java
glint/src/main/java/com/swyp/glint/keyword/application/DrinkingService.java
glint/src/main/java/com/swyp/glint/keyword/application/LocationService.java
glint/src/main/java/com/swyp/glint/keyword/application/ReligionService.java
glint/src/main/java/com/swyp/glint/keyword/application/SmokingService.java
glint/src/main/java/com/swyp/glint/keyword/application/UniversityService.java
glint/src/main/java/com/swyp/glint/keyword/application/WorkCategoryService.java
glint/src/main/java/com/swyp/glint/keyword/application/WorkMappingService.java
glint/src/main/java/com/swyp/glint/keyword/application/WorkService.java
glint/src/main/java/com/swyp/glint/keyword/domain/Work.java
glint/src/main/java/com/swyp/glint/keyword/domain/WorkCategory.java
glint/src/main/java/com/swyp/glint/keyword/repository/WorkCategoryRepository.java
glint/src/main/java/com/swyp/glint/user/application/UserProfileService.java
glint/src/main/java/com/swyp/glint/user/application/dto/UserProfileResponse.java
glint/src/main/java/com/swyp/glint/user/domain/UserDetail.java

❗️ 이슈 번호
close #61 
📝 작업 내용
- 회원 프로필의 각 속성들의 Controller에서 delete, create문, update문 및 필요없는 코드 주석처리
- 각 속성들 기능 수정
- Transactional 어노테이션 추가
- 직업 카테고리 기능 수정 및 추가 구현
- 회원 프로필의 닉네임, 나이(생년월일기반), 직업 카테고리 id, 대학 카테고리 id 응답에 같이 반환하도록 수정
🙇🏻‍♂️ 참고사항!
💡 참고 자료

fix : 회원 프로필 기능 수정

---

glint/src/main/java/com/swyp/glint/meeting/api/MeetingController.java
glint/src/main/java/com/swyp/glint/meeting/application/dto/request/JoinConditionRequest.java
glint/src/main/java/com/swyp/glint/meeting/application/dto/request/MeetingRequest.java
glint/src/main/java/com/swyp/glint/meeting/application/dto/response/MeetingInfoResponse.java
glint/src/main/java/com/swyp/glint/meeting/application/dto/response/MeetingResponse.java
glint/src/main/java/com/swyp/glint/meeting/domain/Meeting.java
glint/src/main/java/com/swyp/glint/meeting/domain/MeetingInfo.java
glint/src/main/java/com/swyp/glint/meeting/domain/UserMeetingValidator.java
glint/src/main/java/com/swyp/glint/meeting/domain/validator/SmokingValidator.java

❗️ 이슈 번호
close #59 
📝 작업 내용
- location 반환 수정
- swagger example 부분수정

fix: #59: 미팅관련 api 수정

---

glint/src/main/java/com/swyp/glint/chatting/api/ChatController.java
glint/src/main/java/com/swyp/glint/chatting/config/WebSocketConfig.java

❗️ 이슈 번호
close #73 
📝 작업 내용
- 채팅방 구독 주소 수정

feat: #73: 채팅방 구독 주소 수정

---

glint/build.gradle

❗️ 이슈 번호
close #
📝 작업 내용
🙇🏻‍♂️ 참고사항!
💡 참고 자료

fix: build queryDsl 추가

---

glint/src/main/java/com/swyp/glint/chatting/api/ChatController.java

❗️ 이슈 번호
close #80 
- 유저 프로필 수정시 이미지 함께 수정하지 못함.
- 함께 수정할 수 있도록 변경

fix: #80: 채팅방 response 수정

---

glint/src/main/java/com/swyp/glint/keyword/application/UniversityService.java
glint/src/main/java/com/swyp/glint/keyword/application/WorkService.java
glint/src/main/java/com/swyp/glint/user/api/UserController.java
glint/src/main/java/com/swyp/glint/user/api/UserProfileController.java
glint/src/main/java/com/swyp/glint/user/application/UserDetailService.java
glint/src/main/java/com/swyp/glint/user/application/UserProfileService.java
glint/src/main/java/com/swyp/glint/user/application/UserService.java
glint/src/main/java/com/swyp/glint/user/application/dto/DrinkingResponse.java
glint/src/main/java/com/swyp/glint/user/application/dto/LocationResponse.java
glint/src/main/java/com/swyp/glint/user/application/dto/ReligionResponse.java
glint/src/main/java/com/swyp/glint/user/application/dto/SmokingResponse.java
glint/src/main/java/com/swyp/glint/user/application/dto/UniversityCategoryResponse.java
glint/src/main/java/com/swyp/glint/user/application/dto/UniversityResponse.java
glint/src/main/java/com/swyp/glint/user/application/dto/UserDetailResponse.java
glint/src/main/java/com/swyp/glint/user/application/dto/UserInfoResponse.java
glint/src/main/java/com/swyp/glint/user/application/dto/UserProfileRequest.java
glint/src/main/java/com/swyp/glint/user/application/dto/UserProfileResponse.java
glint/src/main/java/com/swyp/glint/user/application/dto/UserProfileWithDetailResponse.java
glint/src/main/java/com/swyp/glint/user/application/dto/WorkCategoryResponse.java
glint/src/main/java/com/swyp/glint/user/application/dto/WorkResponse.java
glint/src/main/java/com/swyp/glint/user/domain/UserDetail.java
glint/src/main/java/com/swyp/glint/user/repository/UserCustom.java
glint/src/main/java/com/swyp/glint/user/repository/UserProfileCustom.java
glint/src/main/java/com/swyp/glint/user/repository/UserProfileRepository.java
glint/src/main/java/com/swyp/glint/user/repository/UserRepository.java
glint/src/main/java/com/swyp/glint/user/repository/impl/UserProfileRepositoryImpl.java
glint/src/main/java/com/swyp/glint/user/repository/impl/UserRepositoryImpl.java

❗️ 이슈 번호
close #86 
📝 작업 내용
- 유저 프로필 response 수정
- null 처리
- 유저 정보 함께 반환하는 api 추가

fix: #86: 유저 프로필 response 수정

---

glint/src/main/java/com/swyp/glint/user/api/UserController.java

❗️ 이슈 번호
close #86 
📝 작업 내용
- 유저 detail path variable 수정

Fix #86 유저profile response 수정

---

glint/src/main/java/com/swyp/glint/user/api/UserController.java
glint/src/main/java/com/swyp/glint/user/application/dto/UserDetailResponse.java

❗️ 이슈 번호
close #94 
📝 작업 내용
- user detailResponse age 추가

Fix #94 user detailresopnse age 추가

---

glint/src/main/java/com/swyp/glint/meeting/application/dto/request/MeetingRequest.java
glint/src/main/java/com/swyp/glint/meeting/application/dto/response/MeetingResponse.java
glint/src/main/java/com/swyp/glint/user/application/UserProfileService.java
glint/src/main/java/com/swyp/glint/user/application/dto/ReligionResponse.java
glint/src/main/java/com/swyp/glint/user/application/dto/SmokingResponse.java
glint/src/main/java/com/swyp/glint/user/application/dto/UserProfileRequest.java
glint/src/main/java/com/swyp/glint/user/domain/UserDetail.java

❗️ 이슈 번호
close #97 
📝 작업 내용
- userProfile 음주, 종교, 흡연 id 받도록 수정

Fix #97 user profile음주,종교,흡연,id받도록 수정

---

glint/src/main/java/com/swyp/glint/meeting/application/JoinMeetingService.java
glint/src/main/java/com/swyp/glint/meeting/application/MeetingService.java
glint/src/main/java/com/swyp/glint/meeting/application/dto/request/JoinConditionRequest.java
glint/src/main/java/com/swyp/glint/meeting/application/dto/response/JoinConditionResponse.java
glint/src/main/java/com/swyp/glint/meeting/application/dto/response/MeetingResponse.java
glint/src/main/java/com/swyp/glint/meeting/domain/JoinConditionAggregation.java
glint/src/main/java/com/swyp/glint/meeting/domain/JoinConditionElement.java
glint/src/main/java/com/swyp/glint/meeting/domain/Meeting.java
glint/src/main/java/com/swyp/glint/meeting/domain/MeetingAggregation.java
glint/src/main/java/com/swyp/glint/meeting/domain/validator/DrinkingValidator.java
glint/src/main/java/com/swyp/glint/meeting/domain/validator/ReligionValidator.java
glint/src/main/java/com/swyp/glint/meeting/domain/validator/SmokingValidator.java
glint/src/main/java/com/swyp/glint/meeting/repository/Impl/MeetingRepositoryImpl.java
glint/src/main/java/com/swyp/glint/meeting/repository/JoinMeetingRepository.java
glint/src/main/java/com/swyp/glint/user/application/UserService.java

❗️ 이슈 번호
close #97 
📝 작업 내용
- userProfile 음주, 종교, 흡연 id 받도록 수정

fix: #97: userProfile 음주, 종교, 흡연 id 받도록 수정

---

glint/src/main/java/com/swyp/glint/common/exception/ErrorCode.java
glint/src/main/java/com/swyp/glint/meeting/api/JoinMeetingController.java
glint/src/main/java/com/swyp/glint/meeting/api/MeetingController.java
glint/src/main/java/com/swyp/glint/meeting/application/JoinMeetingService.java
glint/src/main/java/com/swyp/glint/meeting/application/MeetingFacade.java
glint/src/main/java/com/swyp/glint/meeting/application/MeetingService.java
glint/src/main/java/com/swyp/glint/meeting/application/dto/response/JoinConditionResponse.java
glint/src/main/java/com/swyp/glint/meeting/application/dto/response/MeetingInfoResponse.java
glint/src/main/java/com/swyp/glint/meeting/application/dto/response/MeetingInfoResponses.java
glint/src/main/java/com/swyp/glint/meeting/domain/JoinMeeting.java
glint/src/main/java/com/swyp/glint/meeting/domain/JoinStatus.java
glint/src/main/java/com/swyp/glint/meeting/domain/Meeting.java
glint/src/main/java/com/swyp/glint/meeting/domain/MeetingInfo.java
glint/src/main/java/com/swyp/glint/meeting/domain/MeetingStatus.java
glint/src/main/java/com/swyp/glint/meeting/domain/NextMeetingLeader.java
glint/src/main/java/com/swyp/glint/meeting/exception/NotFoundNextMeetingLeader.java
glint/src/main/java/com/swyp/glint/meeting/repository/JoinMeetingRepository.java
glint/src/main/java/com/swyp/glint/user/application/UserProfileService.java
glint/src/main/java/com/swyp/glint/user/domain/Gender.java
glint/src/main/java/com/swyp/glint/user/domain/User.java

❗️ 이슈 번호
close #102 
📝 작업 내용
- 미팅 나가기 api 개발

feat: #102: 미팅 나가기

---

glint/src/main/java/com/swyp/glint/user/api/UserDetailController.java
glint/src/main/java/com/swyp/glint/user/application/dto/UserProfileImageRequest.java

❗️ 이슈 번호
close #101 
📝 작업 내용
- userProfileImage 단독으로 변경할 수 있는 api 추가
🙇🏻‍♂️ 참고사항!
💡 참고 자료

fix: #101: userProfile 이미지 변경 api 추가

---

glint/src/main/java/com/swyp/glint/chatting/api/ChatRoomController.java
glint/src/main/java/com/swyp/glint/keyword/application/UniversityService.java
glint/src/main/java/com/swyp/glint/user/api/UserDetailController.java
glint/src/main/java/com/swyp/glint/user/application/UserDetailService.java
glint/src/main/java/com/swyp/glint/user/application/UserProfileService.java
glint/src/main/java/com/swyp/glint/user/application/dto/UserProfileRequest.java

❗️ 이슈 번호
close #109 
- 이미지 프로필 파일 받아 수정하도록

Fix #109 프로필 이미지 수정

---

glint/src/main/java/com/swyp/glint/user/api/UserDetailController.java
glint/src/main/java/com/swyp/glint/user/api/UserProfileController.java

❗️ 이슈 번호
close #112 
📝 작업 내용
[Feat] #112 회원 프로필 user id로 조회 기능 추가 (응답 타입 : UserProfileWithDetailResponse)
🙇🏻‍♂️ 참고사항!
💡 참고 자료

[Feat] #112 회원 프로필 user id로 조회 기능 추가

---

glint/src/main/java/com/swyp/glint/user/application/dto/UserProfileResponse.java

❗️ 이슈 번호
close #
📝 작업 내용
[fix]-UserProfileResponse의 religion 오타 수정
🙇🏻‍♂️ 참고사항!
💡 참고 자료

[fix]-UserProfileResponse의 religion 오타 수정

---

glint/src/main/java/com/swyp/glint/GlintApplication.java
glint/src/main/java/com/swyp/glint/meeting/api/MeetingController.java
glint/src/main/java/com/swyp/glint/meeting/application/MeetingService.java
glint/src/main/java/com/swyp/glint/meeting/application/dto/MeetingSearchCondition.java
glint/src/main/java/com/swyp/glint/meeting/repository/Impl/MeetingRepositoryImpl.java
glint/src/main/java/com/swyp/glint/meeting/repository/MeetingRepositoryCustom.java
glint/src/main/java/com/swyp/glint/system/config/QueryDslConfiguration.java
glint/src/main/java/com/swyp/glint/user/repository/impl/UserProfileRepositoryImpl.java
glint/src/main/java/com/swyp/glint/user/repository/impl/UserRepositoryImpl.java

❗️ 이슈 번호
close #70 
📝 작업 내용
- 미팅 title, description 매칭 검색 api 개발
🙇🏻‍♂️ 참고사항!
💡 참고 자료

feat: #70: 미팅 검색

---

glint/src/main/java/com/swyp/glint/meeting/domain/MeetingInfo.java

❗️ 이슈 번호
close #119 
📝 작업 내용
- state + city 에서 state만 반환하도록 수정
🙇🏻‍♂️ 참고사항!
💡 참고 자료

fix: #119: 미팅 location 반환 형식 수정

---

glint/src/main/java/com/swyp/glint/meeting/api/MeetingController.java
glint/src/main/java/com/swyp/glint/meeting/application/MeetingService.java
glint/src/main/java/com/swyp/glint/meeting/repository/MeetingRepository.java
glint/src/main/java/com/swyp/glint/meeting/repository/MeetingRepositoryCustom.java
glint/src/main/java/com/swyp/glint/meeting/repository/impl/MeetingRepositoryImpl.java

❗️ 이슈 번호
close #123 
📝 작업 내용
- 내미팅 페이징 작업 되어있지 않음
- 페이징 추가
🙇🏻‍♂️ 참고사항!
💡 참고 자료

fix: #123: 내 미팅 페이징 추가

---

glint/src/main/java/com/swyp/glint/meeting/api/MeetingController.java
glint/src/main/java/com/swyp/glint/meeting/repository/impl/MeetingRepositoryImpl.java

❗️ 이슈 번호
close #127 
📝 작업 내용
- 내미팅 ( 참가미팅, 대기미팅 ) 쿼리 수정
🙇🏻‍♂️ 참고사항!
💡 참고 자료

fix: #123: 참가미팅, 대기미팅 쿼리 수정

---

glint/src/main/java/com/swyp/glint/meeting/api/MeetingController.java
glint/src/main/java/com/swyp/glint/meeting/application/MeetingService.java
glint/src/main/java/com/swyp/glint/meeting/application/dto/response/MeetingInfoCountResponses.java
glint/src/main/java/com/swyp/glint/meeting/repository/MeetingRepositoryCustom.java
glint/src/main/java/com/swyp/glint/meeting/repository/impl/MeetingRepositoryImpl.java
glint/src/main/java/com/swyp/glint/user/application/dto/UserMeetingResponse.java

❗️ 이슈 번호
close #130 
📝 작업 내용
- 미팅 Response 수정
- totalCount 추가
🙇🏻‍♂️ 참고사항!
💡 참고 자료

fix: #130: 미팅 Response 수정 totalCount 추가

---

glint/src/main/java/com/swyp/glint/meeting/repository/impl/MeetingRepositoryImpl.java
glint/src/main/java/com/swyp/glint/searchkeyword/api/DeleteSearchKeywordRequest.java
glint/src/main/java/com/swyp/glint/searchkeyword/api/SearchKeywordController.java
glint/src/main/java/com/swyp/glint/searchkeyword/application/SearchKeywordService.java
glint/src/main/java/com/swyp/glint/searchkeyword/domain/SearchKeyword.java
glint/src/main/java/com/swyp/glint/searchkeyword/repository/OrderByNull.java
glint/src/main/java/com/swyp/glint/searchkeyword/repository/SearchKeywordRepository.java
glint/src/main/java/com/swyp/glint/searchkeyword/repository/SearchKeywordRepositoryCustom.java
glint/src/main/java/com/swyp/glint/searchkeyword/repository/impl/SearchKeywordRepositoryImpl.java

❗️ 이슈 번호
close #70 
📝 작업 내용
- 삭제 추가
- 중복 제거

Feat #70 검색

---

glint/src/main/java/com/swyp/glint/searchkeyword/api/SearchKeywordController.java

❗️ 이슈 번호
close #70 
📝 작업 내용
- 검색 삭제 수정
🙇🏻‍♂️ 참고사항!
💡 참고 자료

fix: #70: 검색 삭제 수정

---

glint/src/main/java/com/swyp/glint/user/application/UserDetailService.java
glint/src/main/java/com/swyp/glint/user/application/UserService.java
glint/src/main/java/com/swyp/glint/user/application/dto/UserLoginResponse.java
glint/src/main/java/com/swyp/glint/user/domain/UserDetail.java

❗️ 이슈 번호
close #149 
- userDetail 없을경우 체크 추가
📝 작업 내용
🙇🏻‍♂️ 참고사항!
💡 참고 자료

fix: 로그인시 회원가입, 기존회원 로그인 여부 추가

---

glint/src/main/java/com/swyp/glint/auth/application/social/KakaoOauth.java
glint/src/main/java/com/swyp/glint/common/exception/ErrorCode.java
glint/src/main/java/com/swyp/glint/meeting/api/MeetingController.java
glint/src/main/java/com/swyp/glint/meeting/application/MeetingFacade.java
glint/src/main/java/com/swyp/glint/meeting/application/MeetingService.java
glint/src/main/java/com/swyp/glint/meeting/domain/Meeting.java
glint/src/main/java/com/swyp/glint/meeting/exception/AlreadyJoinMeetingException.java
glint/src/main/java/com/swyp/glint/user/application/UserProfileService.java

❗️ 이슈 번호
close #158 
📝 작업 내용
- 미팅방 수정
- 참가한 인원모두 조건 만족할 경우 수정 가능
🙇🏻‍♂️ 참고사항!
💡 참고 자료

Feat #158 미팅방 수정

---

glint/src/main/java/com/swyp/glint/auth/filter/JwtLoginFilter.java
glint/src/main/java/com/swyp/glint/meeting/application/MeetingFacade.java
glint/src/main/java/com/swyp/glint/meeting/application/dto/request/JoinConditionRequest.java
glint/src/main/java/com/swyp/glint/meeting/domain/UserMeetingValidator.java
glint/src/main/java/com/swyp/glint/user/application/UserDetailService.java
glint/src/main/java/com/swyp/glint/user/application/UserProfileService.java
glint/src/main/java/com/swyp/glint/user/domain/UserProfile.java
glint/src/main/java/com/swyp/glint/user/repository/UserProfileRepository.java

❗️ 이슈 번호
close #158 
📝 작업 내용
- 미팅방 수정 검증 버그 수정
🙇🏻‍♂️ 참고사항!
💡 참고 자료

feat: 미팅방 수정

---

glint/src/main/java/com/swyp/glint/meeting/application/MeetingFacade.java
glint/src/main/java/com/swyp/glint/meeting/domain/Meeting.java
glint/src/main/java/com/swyp/glint/meeting/repository/impl/MeetingRepositoryImpl.java

❗️ 이슈 번호
close #163 
📝 작업 내용
- 미팅방 검색 조건 location 추가
🙇🏻‍♂️ 참고사항!
💡 참고 자료

fix: 미팅방 검색 location 추가

---

glint/src/main/java/com/swyp/glint/meeting/application/dto/MeetingSearchCondition.java
glint/src/main/java/com/swyp/glint/meeting/repository/impl/MeetingRepositoryImpl.java

❗️ 이슈 번호
close #166
📝 작업 내용
미팅 검색시 locationId를 통해 필터링 할 수 있도록 수정
🙇🏻‍♂️ 참고사항!
💡 참고 자료

fix: 미팅 검색 지역 필터 추가

---

glint/src/main/java/com/swyp/glint/meeting/application/MeetingFacade.java
glint/src/main/java/com/swyp/glint/meeting/repository/JoinMeetingRepository.java

❗️ 이슈 번호
close #169 
📝 작업 내용
- 미팅 중복신청시 Exception 추가
🙇🏻‍♂️ 참고사항!
💡 참고 자료

fix: 미팅 참가 신청 중복신청 못하도록 수정

---

glint/src/main/java/com/swyp/glint/meeting/application/JoinMeetingService.java
glint/src/main/java/com/swyp/glint/meeting/application/MeetingFacade.java
glint/src/main/java/com/swyp/glint/meeting/application/dto/response/MeetingResponse.java
glint/src/main/java/com/swyp/glint/meeting/domain/MeetingAggregation.java

❗️ 이슈 번호
close #173 
📝 작업 내용
미팅조회 참가대기 유저ID 추가
🙇🏻‍♂️ 참고사항!
💡 참고 자료

fix: 미팅조회 참가대기 유저ID 추가

---

glint/src/main/java/com/swyp/glint/meeting/application/JoinMeetingService.java
glint/src/main/java/com/swyp/glint/meeting/application/MeetingFacade.java
glint/src/main/java/com/swyp/glint/meeting/application/dto/response/MeetingResponse.java
glint/src/main/java/com/swyp/glint/meeting/domain/MeetingAggregation.java
glint/src/main/java/com/swyp/glint/meeting/repository/JoinMeetingRepository.java

Develop -> Release Meger #173  미팅조회 참가대기 유저ID 추가

---

glint/src/main/java/com/swyp/glint/meeting/application/MeetingFacade.java
glint/src/main/java/com/swyp/glint/meeting/domain/NextMeetingLeader.java
glint/src/main/resources/application.yaml

❗️ 이슈 번호
close #178 
📝 작업 내용
미팅 생성시 바로 채팅방 열리도록 수정
🙇🏻‍♂️ 참고사항!
💡 참고 자료

Feat #178 미팅 생성시 바로 채팅방 열리도록 수정

---

glint/src/main/java/com/swyp/glint/chatting/api/ChatController.java
glint/src/main/java/com/swyp/glint/chatting/application/ChatRoomService.java
glint/src/main/java/com/swyp/glint/meeting/application/MeetingFacade.java
glint/src/main/java/com/swyp/glint/meeting/domain/UserMeetingValidator.java

❗️ 이슈 번호
close #178
미팅 생성시 바로 채팅방 열리도록 수정

Develop -> Release Merge #178 미팅 생성시 바로 채팅방 열리도록 수정
